################### Cloudflarebeat Configuration Example #########################

############################# Cloudflarebeat ######################################

cloudflarebeat:
  # Defines how often an event is sent to the output
  api_key: "abc123efg456hij789"
  email: "youremail@example.com"
  zone_tag: "yourzonetag"

#================================ Outputs =====================================

# Configure what outputs to use when sending the data collected by the beat.
# Multiple outputs may be used.

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  ssl.key: "/etc/pki/client/cert.key"

